### ISSUE TITLE
ERB tags nested in escaped blocks are skipped

### ISSUE THREAD

**Issue by toncid** [jeremyevans/erubi#11]
Hello, 

I'm importing a ticket from Erubis: https://github.com/kwatch/erubis/issues/6

Also, the same bug report on other channels:
* Rails: https://github.com/rails/rails/issues/18098
* Ruby: https://bugs.ruby-lang.org/issues/10630

---

It seems that Erubis doesn't handle well tags embedded within another tag. My goal is to produce ERB code with some values prefilled in the first pass.

Input ERB code:

```
    <div>
        <%%= Results: <%= 'first' %> | <%= 'second' %> | <%= 'third' %> %>
    </div>
```

Produces the following output:

```
    <div>
        <%= Results: <%= 'first' %> | second | third %>
    </div>
```

Expected output is:

```
    <div>
        <%= Results: first | second | third %>
    </div>
```

The first nested ERB tag is skipped. The same happens when there is just one block nested.

**Comment by jeremyevans** [comment]
Erubi emulates Erubis behavior, not ERB behavior, so this is not considered a bug as Erubis behaves the same way.

**Comment by toncid** [comment]
But this is just plain wrong. What's the point od Erubi if it's not supposed to behave correctly?

**Comment by jeremyevans** [comment]
I don't consider this "plain wrong" or wrong at all.  Erubis behavior is different than ERB behavior, and Erubi follows Erubis behavior.

Note that ERB behavior for nested tags is still not even documented, and the ERB tests for nested tags were not added until after the release of Erubis 2.5.0.

To get the output you want, I recommend:

```
<<% %>%= Results: <%= 'first' %> | <%= 'second' %> | <%= 'third' %> %>
```

**Comment by toncid** [comment]
Ha! :) I'll give it a try. Thanks!

**Comment by yogeshjain999** [comment]
Thanks @jeremyevans , that totally works!
