### ISSUE TITLE
ERB comment inside JS comment remove a line break

### ISSUE THREAD

**Issue by MichaelKuhinica** [jeremyevans/erubi#14]
We found this issue with some exotic comments in our code base after upgrading our Rails project from `5.0.5` to `5.1.3`.

The block:
```
<script>
  // <%# Exotic comment %>
  console.log('foo');
</script>
```

Gets evaluated to:
```
<script>
  //     console.log('foo');
</script>
```

I am not sure if it's `erubi`, though. What do you think?

**Comment by MichaelKuhinica** [comment]
Here are a few more examples using `erubi (1.7.0)`:

Line break intact:

```
irb(main):006:0> eval(Erubi::Engine.new("// \nnew line\n").src)
=> "// \nnew line\n"
```

Bad, strips all whitespace around itself, including the line break:
```
irb(main):004:0> eval(Erubi::Engine.new("// <%# comment %> \nnew line\n").src)
=> "// new line\n"
```

**Comment by AlexWayfer** [comment]
From Erubis description:

> Spaces around '<% %>' are trimmed automatically only when '<%' is at the beginning of line and '%>' is at the end of line.

So… it looks like a bug.

**Comment by jeremyevans** [comment]
Thanks for the report. This does appear to be a difference between how Erubis handles this and how Erubi does:

```ruby
eval(Erubis::Eruby.new("// <%# comment %> \nnew line\n").src)
# => "//  \nnew line\n"
```

This appears to be specific to `<%#` tags.  The fix is fairly simple, and similar to a previous fix for `<%` tags.   I'll upload the fix with a spec shortly.
