### ISSUE TITLE
Make `<%=` tag swallow/delete leading spaces as well

### ISSUE THREAD

**Issue by jschulenklopper** [jeremyevans/erubi#19]
See https://stackoverflow.com/questions/53167613/how-to-trim-leading-whitespace-with-in-erb-templates-in-rails-that-end-up.

I believe that the `<%-` opening and `-%>` closing tags are swallowing leading and trailing whitespace (newlines and/or space). Somehow, there's no way (that I know, i.c., is documented) to make the `<%=` opening tag to swallow leading spaces.

Request: make an option or variant of the `<%=` tag to swallow leading spaces, e.g., via a `<%=-` tag.

**Comment by jeremyevans** [comment]
Erubi attempts to implement the Erubis tag support, and Erubis didn't support this, so I don't want to add support for it (stdlib ERB doesn't support it either).  For the linked issue, I recommend just placing the `<%=` at the beginning of the line.

Note that Erubi does support subclasses that modify the parser and add support for new tags.  Erubi ships with an example of doing this (`erubi/capture_end`).  You could use such support to add a `<%=-` tag.  Rails does subclass Erubi::Engine, so you would have to subclass their subclass and then switch the Rails' `erb_implementation` to your subclass.

**Comment by AlexWayfer** [comment]
> stdlib ERB doesn't support it either

There is `:trim_mode` option for `ERB.new`, which, for example, can accept `'-'` value for `-%>` tags.

https://ruby-doc.org/stdlib-3.0.1/libdoc/erb/rdoc/ERB.html#method-c-new

At least since Ruby 2.3 it exists.

**Comment by jeremyevans** [comment]
@AlexWayfer That's not what @jschulenklopper asked for.  `ERB` doesn't support trim_mode for leading whitespace for `<%=-` opening tags:

```ruby
ERB.new("  <% '' -%>\n", trim_mode: '-').result(binding)
# => "  "
ERB.new("  <%= '' -%>\n", trim_mode: '-').result(binding)
# => "  "
 ERB.new("  <%- '' -%>\n", trim_mode: '-').result(binding)
# => ""
ERB.new("  <%=- '' -%>\n", trim_mode: '-').result(binding)
# => "  "
```

Even if `ERB` did, `Erubis` doesn't, and `Erubis` compatibility is what `Erubi` aims for.

**Comment by AlexWayfer** [comment]
Oh, sorry, didn't notice the importance of `=` in the issue, looked for similar but just `<%`. Yes, it's strange, but `<%-` works and `<%=-` doesn't (although it doesn't raise an exception like `<%-=`).

**Comment by jeremyevans** [comment]
`"  <%=- '' -%>\n"` is parsed as `"  <%=(- '') -%>\n"`, which is why it works on Ruby 2.3+ and not 2.2 and below (String#-@ was added in Ruby 2.3).
