### ISSUE TITLE
CLI interface

### ISSUE THREAD

**Issue by dluciv** [jeremyevans/erubi#21]
First, than you for your nice project!

Than the case itself: why not consider adding CLI script to use Erubi from shell, like Erb or Ember? Erubi would be very useful in standalone, I think.

**Comment by AlexWayfer** [comment]
It can be implemented with external (additional) gem.

**Comment by jeremyevans** [comment]
I agree, something like an erubi-bin gem would be the way to go for this.  My main concern with shipping something like this with Erubi would be trying to support all of the options that Erubi supports via command line options, as well as tests for all of those options, would be a lot of work and require extra maintenance if new features are added to Erubi.
