### ISSUE TITLE
How to make both yielding partials and Forme work with capture_end engine?

### ISSUE THREAD

**Issue by janko** [jeremyevans/erubi#24]
I'm setting a new application which uses dry-view, which internally uses Tilt.

Initially I wanted to set up Forme, and in order for the Forme's ERB form to work, I had to pass `outvar: "@_out_buf"` option to Tilt.

Next I also wanted to implement partial rendering, where partials have a `<%= yield %>`. However, this doesn't seem to work correctly, in the sense that I get the content rendered twice:

```rb
require "tilt"
require "tilt/erubi"
require "erubi/capture_end"

def render(filename, &block)
  tilt = Tilt.new(filename, engine_class: Erubi::CaptureEndEngine, outvar: "@_out_buf")
  tilt.render(self, &block)
end

puts render("filename.erb")
```
```erb
<!-- filename.erb -->
<%|= render "page.erb" do %>
  <p>Some text</p>
<%| end %>
```
```erb
<!-- page.erb -->
<div class="foo">
  <%= yield %>
</div>
```
```
# output
<div class="foo">

  <p>Some text</p>
<div class="foo">

  <p>Some text</p>

</div>
```

Note that this issue only happens when I explicitly set `:outvar` to an instance variable. However, I need that in order for Forme to work.

---------

As I was writing this, I tried to replace `<%= yield %>` with `<% yield %>`, and that worked. However, I wouldn't like this to be necessary, as I'm already using `<%= yield %>` in my layout template, and it works (it would be great if I could use `<%= yield %>` everywhere and that it works).

Also, I was reading up on the rationale behind the `<%|= foo do %> ... <%| end %>` syntax, however, I feel like it creates an overhead for people coming from Rails. Would it make sense / be possible to write an alternative engine that makes capturing work with `<%= foo do %> ... <% end %>`? It's just that I'm having a hard time setting up templating outside of Rails, and would like to investigate whether I can help remove barriers that I've encountered.

**Comment by janko** [comment]
Scratch the last paragraph, if it requires having to parse Ruby code with regexes, that seems to be an argument enough. I'm just wondering whether that ever caused problems with Rails, as it sounds very brittle.

**Comment by jeremyevans** [comment]
The problem you are running into is that `<%= yield %>` ends up running the equivalent of:

```ruby
@_out_buf << @_out_buf
```

This is because `<%=` roughly translates into `@_out_buf <<`, and `yield` in this case returns `@_out_buf`, because that is the last expression the block returns.

Other than using `<% yield %>`, which you don't want to do, here are a couple additional options.  The first one is ugly and I don't think you will like it:

```
<%|= render("page.erb") do %>
  <p>Some text</p>
<%| ; nil end %>
```

The second one involves defining a separate method to use in this case:

```
def partial(*args)
  render(*args) do
    yield
    nil
  end
end
```

Then you can use:

```
<%|= partial("page.erb") do %>
  <p>Some text</p>
<%| end %>
```

Both cases make sure `@_out_buf` isn't the return value of the block, so you aren't appending to the same object.

Personally, I would take the `<% yield %>` approach.

In terms of changing the internals of Erubi so what you propose could work correctly, I'm not sure how feasible it is.  The following code would fix your case by reassigning `@_out_buf` temporarily inside the block in addition to before and after the block:

```diff
diff --git a/lib/erubi/capture_end.rb b/lib/erubi/capture_end.rb
index 5bc04f7..24b2883 100644
--- a/lib/erubi/capture_end.rb
+++ b/lib/erubi/capture_end.rb
@@ -37,12 +37,13 @@ module Erubi
         add_text(lspace) if lspace
         escape_capture = !((indicator == '|=') ^ @escape_capture)
         src << "begin; (#{@bufstack} ||= []) << #{@bufvar}; #{@bufvar} = #{@bufval}; #{@bufstack}.last << #{@escapefunc if escape_capture}((" << code
+        src << "begin; (#{@bufstack} ||= []) << #{@bufvar}; #{@bufvar} = #{@bufval}; "
         add_text(rspace) if rspace
       when '|'
         rspace = nil if tailch && !tailch.empty?
         add_text(lspace) if lspace
         result = @yield_returns_buffer ? " #{@bufvar}; " : ""
-        src << result << code << ")).to_s; ensure; #{@bufvar} = #{@bufstack}.pop; end;"
+        src << result << code << "; ensure; #{@bufvar} = #{@bufstack}.pop; end; )).to_s; ensure; #{@bufvar} = #{@bufstack}.pop; end;"
         add_text(rspace) if rspace
       else
         super
```

However, it breaks most of the tests, because it doesn't work correctly when the method you are calling (e.g. `render` in your case) is modifying the bufvar (`@_out_buf` in your case).

**Comment by janko** [comment]
Thank you, this gives me plenty to work with. I like the option of defining a separate method that returns nil, and I will reconsider using `<% yield %>`.

I’m thinking that it would be good to add this caveat to the README.

**Comment by janko** [comment]
Thank you, this gives me plenty to work with. I like the option of defining a separate method that returns nil, and I will reconsider using `<% yield %>`.

I’m thinking that it would be good to add this caveat to the README.

**Comment by jeremyevans** [comment]
I'll accept a PR for the README.  Note that for your particular issue, instead of trying to handle it in Erubi, you may want to look into adding support to Forme for working with the CaptureEnd engine.  This may work similar to the Rails's Forme support, instead of the current Forme ERB support.

**Comment by janko** [comment]
Thanks for the suggestion, I'll look into that.

**Comment by AlexWayfer** [comment]
Another suggestion: use different variables.

```ruby
def render(filename, tilt: {}, &block)
  tilt_options =
    { engine_class: Erubi::CaptureEndEngine, outvar: "@_out_buf" }.merge(tilt)
  tilt = Tilt.new(filename, **tilt_options)
  tilt.render(self, &block)
end
```

```erb
# filename.erb
<%|= render "page.erb", tilt: { outvar: "@_internal" } do %>
  <p>Some text</p>
<%| end %>
```

**Comment by janko** [comment]
Thanks for the suggestion. Unfortunately dry-view which I'm using doesn't allow me to modify Tilt settings at runtime AFAIK.

**Comment by AlexWayfer** [comment]
> Unfortunately, dry-view which I'm using doesn't allow me to modify Tilt settings at runtime as far as I can see.

It can be added to the `dry-view`, I think.

**Comment by janko** [comment]
I was able to come up with something that seems to work with default Erubi configuration (so without outvar being an instance variable):

```rb
class MyForm < Forme::Form
  # If a block is given, inject an opening tag into the
  # output, inject any given children into the output, yield to the
  # block, inject a closing tag into the output.
  # If a block is not given, just return the tag created.
  def tag(type, attr={}, children=[], &block)
    tag = _tag(type, attr, children)

    if block
      capture(block) do
        emit(serialize_open(tag))
        Array(tag.children).each{|c| emit(c)}
        yield self
        emit(serialize_close(tag))
      end
    else
      tag
    end
  end

  def emit(tag)
    @output << tag.to_s
  end

  private

  def capture(block)
    # make sure that we're also appending to Erubi's buffer
    @output = eval("_buf", block.binding)
    yield
    # make Forme return the accumulated buffer as return value
    @output
  end
end
```

When I run the following:

```rb
def render(filename, &block)
  tilt = Tilt.new(filename, engine_class: Erubi::CaptureEndEngine)
  tilt.render(self, &block)
end

def form(attrs, &block)
  hidden_tag = Forme::Form.new.tag(:input, type: :hidden)

  MyForm.form(attrs, hidden_tags: [hidden_tag], &block)
end

puts render("foo.erb")
```
```erb
<!-- foo.erb -->
before bar
<%|= render "bar.erb" do %>
  before baz
  <%|= form action: "/foo", method: "post" do |f| %>
    <%= f.input :text %>
    <%|= render "baz.erb" do %>
      inside baz
    <%| end %>
    <%= f.button "Submit" %>
  <%| end %>
  after baz
<%| end %>
after bar
```
```rb
<!-- bar.erb -->
before bar yield
<%= yield %>
after bar yield
```
```rb
<!-- baz.erb -->
before baz yield
<%= yield %>
after baz yield
```

I seem to get the correct output:

```
before bar
before bar yield

  before baz
  <form action="/foo" method="post"><input type="hidden"/>
    <input type="text"/>
    before baz yield

      inside baz

after baz yield

    <input type="submit" value="Submit"/>
  </form>
  after baz

after bar yield

after bar
```

@jeremyevans Does that look ok to you? It doesn't follow exactly the Rails integration, so I don't know if it works for all cases.

**Comment by jeremyevans** [comment]
It looks reasonable.  I'd definitely like to upstream working support into Forme.  If you you are interested in that, you probably want to copy the existing roda integration tests from Forme and modify them to use the capture_end ERB syntax and that will be a decent test that everything is working.
