### ISSUE TITLE
Need a way to configure the escaped tag delimiter

### ISSUE THREAD

**Issue by jaredcwhite** [jeremyevans/erubi#26]
I'm using Erubi as the basis for an ERB variant which uses `{% %}` instead of `<% %>`, and because the regex is customizable that's easy to do…however, for the escaping feature (normally `<%% %>` is converted to the text output `<% %>`), there's no way to change that. My `{%% %}` gets output back as `<% %>`.

I'd be happy to file a PR if this is something you want to include in Erubi…otherwise I'll have to figure out a monkeypatch.

**Comment by AlexWayfer** [comment]
> however, for the escaping feature (normally `<%% %>` is converted to the text output `<% %>`)

I see `<%==` in the documentation, are you sure about correct issue?

**Comment by jeremyevans** [comment]
I'll accept :escape_prefix and :escape_postfix options, so you can do `escape_prefix: '{%', escape_postfix: '%}'`.

**Comment by jaredcwhite** [comment]
@jeremyevans That would be cool…I wonder if "escape" is the best term to use though (judging from @AlexWayfer's comment), since it's the delimiter itself that is escaping from being processed, not the escaping of strings within the template.

**Comment by jeremyevans** [comment]
That's fair.  If you can think of a better prefix than `escape`, I'd probably be open to it.

**Comment by AlexWayfer** [comment]
Oh, sorry, didn't get it. I've used `<%= "\<% ... %\>" %>` (or you can use `<\%` as I remember), but it's not comfortable, yes. Now I know!

**Comment by jaredcwhite** [comment]
How about literal_prefix/suffix?

**Comment by jeremyevans** [comment]
I think that works.

**Comment by jaredcwhite** [comment]
Cool, I'll send over a PR for that soon.
