### ISSUE TITLE
[Feature Request] Add a erubis binary for support check erb syntax. (and a replacement for old erubis)

### ISSUE THREAD

**Issue by zw963** [jeremyevans/erubi#30]
[erubis](https://github.com/kwatch/erubis) never update since 10 years ago, but my editor (emacs, use flycheck to check syntax), still need `erubis` command which provided by this old gem to check ERB file syntax.

```sh
 ╰─ $ erubis -z index.erb 
index.erb:10: syntax error, unexpected ';', expecting ')'
...st-institutions', 'ID', 'id' ); _buf << '</th>
... 
```

Do you consider to support this?

Thank you.

**Comment by zw963** [comment]
Oh, i find a new checker, it works too, and seem like still live maintained.

https://github.com/ericqweinstein/ruumba

Thank you.

**Comment by zw963** [comment]
BTW, though `ruumba` is not same things as `erubis`,  latter is a syntax checker, and former is a Rubocop like tool for erb.

**Comment by jeremyevans** [comment]
I don't want to support the `erubis` binary.  There are actually a lot of things that Erubis provides that Erubi does not provide.  Erubi only attempts to be compatible with Erubis in terms of erb syntax (other than the bug fixes and differences noted in the README).
