### ISSUE TITLE
Gem signing

### ISSUE THREAD

**Issue by josegomezr** [jeremyevans/erubi#36]
Hi there!

I've been experimenting on enabling `--trust-policy` on my bundler installs and it breaks with this gem (probably with some others along the chain, but this was the first alert).

Given the amount of downloads, and the fact that this gem is bundled with `actionview` in basically every rails installation, it's a very important part of the supply chain for rails projects.

My question is: Is there any plans to enable gem signing so consumers can install with `--trust-policy=HighSecurity` ?

**Comment by josegomezr** [comment]
well, giving it some more rounds of installs it seems like bunch of gems are failing to fulfill the `HighSecurity` Policy including `aws-partitions`, `msgpack`, etc. etc.

Doesn't look like it got traction in the ecosystem.

**Comment by jeremyevans** [comment]
No plans to enable gem signing.  MFA is enabled in Rubygems for all people that can release the erubi gem.
