### ISSUE TITLE
Support to comment out erb tags

### ISSUE THREAD

**Issue by k0kubun** [jeremyevans/erubi#6]
This concept is originally reported by @Adamantish in https://bugs.ruby-lang.org/issues/11624.

## Proposal
For Erubi maintainers, how do you feel for supporting following syntax (`<#--` and `--#>`)?

```
<#--
None of this will be outputted: <%= my_ruby_var %>
and neither will this
--#>
```

There seem to be some use cases in Rails:

- https://stackoverflow.com/questions/3127644/block-comments-in-html-erb-templates-in-rails
- https://stackoverflow.com/questions/3901619/how-to-comment-lines-in-rails-html-erb-files

## Detail discussion
I created reference implementation based on ERB https://github.com/k0kubun/erb-comment.
But I decided not to introduce this to ERB because of compiling cost and thought it would be good to introduce it to Erubi. Erubi is already an extension of ERB in terms of syntax for `<%==`.

I want to hear the thoughts about them.

**Comment by jeremyevans** [comment]
As this syntax is not compatible with Erubis, I do not think it should be supported.  You can use one of the following approaches instead:

```
<% if false %>
None of this will be outputted: <%= my_ruby_var %>
and neither will this
<% end %>
```

```
<% (<<'END') if false %>
None of this will be outputted: <%= my_ruby_var %>
and neither will this
<%
END%>
```

```
<%
=begin
%>
None of this will be outputted: <%= my_ruby_var %>
and neither will this
<%
=end
%>
```

**Comment by k0kubun** [comment]
While I didn't comment intentionally, I personally like `<% if false %>` too. Thank you for your comment.
